export interface LeaderboardEntry {
  rank: number;
  name: string;
  project: string;
  vibePoints: number;
  avatar: string;
  avatarAlt: string;
}

export const leaderboard = {
  eyebrow: 'The Rankings',
  heading: 'The Scoreboard Build With AI - Agentic Premier League',
  tabs: ['Overall Event Series', 'Match-by-Match'],
  entries: [
    {
      rank: 1,
      name: 'Gamebit',
      project: 'Gamebit',
      vibePoints: 27,
      avatar: '/images/profile-aravind.jpg',
      avatarAlt: 'Portrait of Aravind Sharma',
    },
    {
      rank: 2,
      name: 'BJP',
      project: 'Bhartiya Janta Party (BJP)',
      vibePoints: 26,
      avatar: '/images/profile-priya.jpg',
      avatarAlt: 'Portrait of Priya Patel',
    },
    {
      rank: 3,
      name: 'Pushparaj Singhal',
      project: '',
      vibePoints: 25,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 4,
      name: 'Munish jain',
      project: '',
      vibePoints: 25,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 4,
      name: 'Munish jain',
      project: '',
      vibePoints: 25,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
     {
      rank: 5,
      name: 'Build Algos',
      project: '',
      vibePoints: 24,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 6,
      name: 'Codex',
      project: '',
      vibePoints: 24,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 7,
      name: 'Team ethics',
      project: '',
      vibePoints: 23,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 8,
      name: 'Kushagra misra',
      project: '',
      vibePoints: 23,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 9,
      name: 'StadiumPulse',
      project: '',
      vibePoints: 23,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 10,
      name: 'Ethics',
      project: '',
      vibePoints: 22,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 11,
      name: 'Samyak choudhary ',
      project: '',
      vibePoints: 22,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 12,
      name: 'Hustlers',
      project: '',
      vibePoints: 21,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 13,
      name: 'Faluda',
      project: '',
      vibePoints: 21,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
     {
      rank: 14,
      name: 'Byte Avengers ',
      project: '',
      vibePoints: 17,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
     {
      rank: 15,
      name: 'Rockcode',
      project: '',
      vibePoints: 17,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 16,
      name: 'Samyak Choudhary ',
      project: '',
      vibePoints: 10,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 17,
      name: 'Dropcode ',
      project: '',
      vibePoints: 9,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
    {
      rank: 18,
      name: 'UP187 ',
      project: '',
      vibePoints: 9,
      avatar: '/images/profile-rohan.jpg',
      avatarAlt: 'Portrait of Rohan Verma',
    },
  ] satisfies LeaderboardEntry[],
};
